### ISSUE TITLE
Trapezoid Isn't Tangent to Opposite Sides

### ISSUE THREAD

**Issue by CLiu13** [CLiu13/ProjectorOS#1]
The trapezoid is supposed to  be tangent to opposite sides. Right now one side of the trapezoid is shared  with the square, but the parallel side of the trapezoid should share the other parallel side of the square.

Diagram:

A-----E-----F-------B
|       /        \         |
|      /          \        |
|    /             \       |
|  /                \      |
D-------------------C

Notice square ABCD and trapezoid EFCD. EF is on AB, and DC is DC.

**Comment by bryanzhou07** [comment]
fixed
